/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author DEL
 */
public class EditCourse extends javax.swing.JFrame {

    /**
     * Creates new form EditCourse
     */
    
    DefaultTableModel model;
    
    
    public EditCourse() {
        initComponents();
        setRecordToTabel();
    }

    
        public void setRecordToTabel(){
        try {
            Connection con=DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("Select * from course");
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                int courseId=rs.getInt("id");              
                String courseName=rs.getString("cname"); 
                String courseAmount = rs.getString("cost");
                
                Object[] obj={courseId,courseName,courseAmount};
                model=(DefaultTableModel)tbl_updateCourse.getModel();
                model.addRow(obj);
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
        public void addCourse(int id,String cname,double cost){
            try {
                Connection con=DBConnection.getConnection();
                PreparedStatement pst=con.prepareStatement("insert into course values(?,?,?)");
                pst.setInt(1, id);
                pst.setString(2, cname);
                pst.setDouble(3, cost);
                int rowCount=pst.executeUpdate();
                if(rowCount==1){
                    JOptionPane.showMessageDialog(this, "Course Added Successfully");
                    clearTable();
                    setRecordToTabel();
                }else{
                    JOptionPane.showMessageDialog(this, "Course Added Failed");                    
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
        public void clearTable(){
            DefaultTableModel model=(DefaultTableModel)tbl_updateCourse.getModel();
            model.setRowCount(0);
            
            
        }
        
        public void updateCourse(int id,String cname,double cost){
            try {
                Connection con=DBConnection.getConnection();
                PreparedStatement pst=con.prepareStatement("update course set  cname =? ,cost = ? where id= ? ");
                pst.setString(1, cname);
                pst.setDouble(2, cost);
                pst.setInt(3, id);
                
                int rowCount=pst.executeUpdate();
                if(rowCount==1){
                    JOptionPane.showMessageDialog(this, "Course Updated Successfully");
                    clearTable();
                    setRecordToTabel();
                }else{
                    JOptionPane.showMessageDialog(this, "Course Updation Faield");                    
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
        public void deleteCourse(int id,String cname,double cost){
            try {
                Connection con=DBConnection.getConnection();
                PreparedStatement pst=con.prepareStatement("delete from course where id=?");              
                pst.setInt(1, id);
                
                int rowCount=pst.executeUpdate();
                if(rowCount==1){
                    JOptionPane.showMessageDialog(this, "Course Deleted Successfully");
                    clearTable();
                    setRecordToTabel();
                }else{
                    JOptionPane.showMessageDialog(this, "Course Deletion Faield");                    
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_updateCourse = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_courseId = new javax.swing.JTextField();
        txt_coueseName = new javax.swing.JTextField();
        txt_coueseAmount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        panelsideBar = new javax.swing.JPanel();
        panalHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        panalSearchRecord = new javax.swing.JPanel();
        btnSearchRecord = new javax.swing.JLabel();
        panalEditCourses = new javax.swing.JPanel();
        btnEditCourses = new javax.swing.JLabel();
        panalCourseList = new javax.swing.JPanel();
        btnCourseList = new javax.swing.JLabel();
        panalViewAllRecord = new javax.swing.JPanel();
        btnViewAllRecord = new javax.swing.JLabel();
        panalBack = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        panalLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Course");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_updateCourse.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        tbl_updateCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Name", "Amount"
            }
        ));
        tbl_updateCourse.setRowHeight(50);
        tbl_updateCourse.setRowMargin(1);
        tbl_updateCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_updateCourseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_updateCourse);
        if (tbl_updateCourse.getColumnModel().getColumnCount() > 0) {
            tbl_updateCourse.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 170, 760, 690));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Course ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 180, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Course Amount :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 230, 60));

        txt_courseId.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jPanel1.add(txt_courseId, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 300, 60));

        txt_coueseName.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        txt_coueseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_coueseNameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_coueseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 300, 60));

        txt_coueseAmount.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        txt_coueseAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_coueseAmountActionPerformed(evt);
            }
        });
        jPanel1.add(txt_coueseAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 300, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Course Name :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 210, 60));

        btn_delete.setBackground(new java.awt.Color(0, 51, 51));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/delete.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 740, 160, 60));

        btn_update.setBackground(new java.awt.Color(0, 51, 51));
        btn_update.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/update.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 740, 160, 60));

        btn_add.setBackground(new java.awt.Color(0, 51, 51));
        btn_add.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/add2.png"))); // NOI18N
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 740, 160, 60));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 860, 1410, 210));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Update Course");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 400, 60));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 570, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/back-button.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 70, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 1070));

        panelsideBar.setBackground(new java.awt.Color(0, 102, 102));
        panelsideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panalHome.setBackground(new java.awt.Color(0, 102, 102));
        panalHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panalHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btnHome.setText("   Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        panalHome.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 290, 70));

        panelsideBar.add(panalHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 330, 70));

        panalSearchRecord.setBackground(new java.awt.Color(0, 102, 102));
        panalSearchRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panalSearchRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearchRecord.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnSearchRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search2.png"))); // NOI18N
        btnSearchRecord.setText("Search Record");
        btnSearchRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseExited(evt);
            }
        });
        panalSearchRecord.add(btnSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 290, 70));

        panelsideBar.add(panalSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 330, 70));

        panalEditCourses.setBackground(new java.awt.Color(0, 102, 102));
        panalEditCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panalEditCourses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditCourses.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnEditCourses.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCourses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btnEditCourses.setText(" Edit Courses");
        btnEditCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseExited(evt);
            }
        });
        panalEditCourses.add(btnEditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 290, 70));

        panelsideBar.add(panalEditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 330, 70));

        panalCourseList.setBackground(new java.awt.Color(0, 102, 102));
        panalCourseList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panalCourseList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCourseList.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnCourseList.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/list.png"))); // NOI18N
        btnCourseList.setText(" Course List");
        btnCourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCourseListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCourseListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCourseListMouseExited(evt);
            }
        });
        panalCourseList.add(btnCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 300, 70));

        panelsideBar.add(panalCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 330, 70));

        panalViewAllRecord.setBackground(new java.awt.Color(0, 102, 102));
        panalViewAllRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panalViewAllRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewAllRecord.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnViewAllRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view all record.png"))); // NOI18N
        btnViewAllRecord.setText("View All Record");
        btnViewAllRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseExited(evt);
            }
        });
        panalViewAllRecord.add(btnViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 300, 70));

        panelsideBar.add(panalViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 330, 70));

        panalBack.setBackground(new java.awt.Color(0, 102, 102));
        panalBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panalBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/back-button.png"))); // NOI18N
        btnBack.setText("  Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        panalBack.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 290, 70));

        panelsideBar.add(panalBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 710, 330, 70));

        panalLogout.setBackground(new java.awt.Color(0, 102, 102));
        panalLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panalLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        btnLogout.setText("  Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        panalLogout.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 290, 70));

        panelsideBar.add(panalLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 820, 330, 70));

        getContentPane().add(panelsideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 0, 500, 1070));

        setSize(new java.awt.Dimension(1927, 1079));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_coueseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_coueseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_coueseNameActionPerformed

    private void txt_coueseAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_coueseAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_coueseAmountActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        int id=Integer.parseInt(txt_courseId.getText());
        String cname=txt_coueseName.getText();
        double cost = Double.parseDouble(txt_coueseAmount.getText());

        updateCourse(id, cname, cost);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateActionPerformed

    private void tbl_updateCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_updateCourseMouseClicked
        int rowNo=tbl_updateCourse.getSelectedRow();
            TableModel model= tbl_updateCourse.getModel();
            txt_courseId.setText(model.getValueAt(rowNo, 0).toString());
            txt_coueseName.setText(model.getValueAt(rowNo, 1).toString());
            txt_coueseAmount.setText((String)model.getValueAt(rowNo, 2));

    }//GEN-LAST:event_tbl_updateCourseMouseClicked

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        int id=Integer.parseInt(txt_courseId.getText());
        String cname=txt_coueseName.getText();
        double cost = Double.parseDouble(txt_coueseAmount.getText());

        addCourse(id, cname, cost);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int id=Integer.parseInt(txt_courseId.getText());
        String cname=txt_coueseName.getText();
        double cost = Double.parseDouble(txt_coueseAmount.getText());

        deleteCourse(id, cname, cost);
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        Home home= new Home();
        home.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        Color clr= new Color(0,153,153);
        panalHome.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        Color clr= new Color(0,103,103);
        panalHome.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnSearchRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseClicked
        SearchRecord searchRecord=new SearchRecord();
        searchRecord.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchRecordMouseClicked

    private void btnSearchRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseEntered
        Color clr= new Color(0,153,153);
        panalSearchRecord.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnSearchRecordMouseEntered

    private void btnSearchRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseExited
        Color clr= new Color(0,103,103);
        panalSearchRecord.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnSearchRecordMouseExited

    private void btnEditCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseClicked
        EditCourse ec = new EditCourse();
        ec.show();
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditCoursesMouseClicked

    private void btnEditCoursesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseEntered
        Color clr= new Color(0,153,153);
        panalEditCourses.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnEditCoursesMouseEntered

    private void btnEditCoursesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseExited
        Color clr= new Color(0,103,103);
        panalEditCourses.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnEditCoursesMouseExited

    private void btnCourseListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseClicked
        ViewCourse vc = new ViewCourse();
        vc.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCourseListMouseClicked

    private void btnCourseListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseEntered
        Color clr= new Color(0,153,153);
        panalCourseList.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnCourseListMouseEntered

    private void btnCourseListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseExited
        Color clr= new Color(0,103,103);
        panalCourseList.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnCourseListMouseExited

    private void btnViewAllRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseClicked
        ViewAllRecords allRecords=new ViewAllRecords();
        allRecords.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewAllRecordMouseClicked

    private void btnViewAllRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseEntered
        Color clr= new Color(0,153,153);
        panalViewAllRecord.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnViewAllRecordMouseEntered

    private void btnViewAllRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseExited
        Color clr= new Color(0,103,103);
        panalViewAllRecord.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnViewAllRecordMouseExited

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        Home home= new Home();
        home.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        Color clr= new Color(0,153,153);
        panalBack.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        Color clr= new Color(0,103,103);
        panalBack.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseExited

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked

        Login login=new Login();
        login.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        Color clr= new Color(0,153,153);
        panalLogout.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        Color clr= new Color(0,103,103);
        panalLogout.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnCourseList;
    private javax.swing.JLabel btnEditCourses;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnSearchRecord;
    private javax.swing.JLabel btnViewAllRecord;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panalBack;
    private javax.swing.JPanel panalCourseList;
    private javax.swing.JPanel panalEditCourses;
    private javax.swing.JPanel panalHome;
    private javax.swing.JPanel panalLogout;
    private javax.swing.JPanel panalSearchRecord;
    private javax.swing.JPanel panalViewAllRecord;
    private javax.swing.JPanel panelsideBar;
    private javax.swing.JTable tbl_updateCourse;
    private javax.swing.JTextField txt_coueseAmount;
    private javax.swing.JTextField txt_coueseName;
    private javax.swing.JTextField txt_courseId;
    // End of variables declaration//GEN-END:variables
}
