/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system;

import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author DEL
 */
public class PrintReciept extends javax.swing.JFrame {

    /**
     * Creates new form PrintReciept
     */
    public PrintReciept() {
        initComponents();
        getRecord();
        Container c= getContentPane();
        c.setBackground(new Color(1,153,153));
    }

    public void getRecord(){
        try{
            Connection con=DBConnection.getConnection();
            PreparedStatement pst=con.prepareStatement("Select * from fees_details order by reciept_no desc limit 1");
           
            pst.executeQuery();
            ResultSet rs= pst.executeQuery();
            rs.next();
            
            txt_receiptNo.setText(""+(rs.getInt(1)));
            txt_recivedFrom.setText(""+(rs.getString(2)));
            txt_paymentMode.setText(""+(rs.getString(3)));
            if(!rs.getString(4).equals(""))
            {
                txt_ddNo.setVisible(false);
                lbl_ddNo.setVisible(false);
                txt_chequeNo.setText(""+(rs.getString(4)));
            }
            if(!rs.getString(5).equals(""))
            {
                txt_bankName.setText(""+(rs.getString(5)));
            }
            if(!rs.getString(6).equals(""))
            {
                txt_chequeNo.setVisible(false);
                lbl_chequeNo.setVisible(false);
                txt_ddNo.setText(""+(rs.getString(6)));
            }
            if(rs.getString(6).equals("") && rs.getString(4).equals(""))
            {
                txt_chequeNo.setVisible(false);
                lbl_chequeNo.setVisible(false);
                txt_ddNo.setVisible(false);
                lbl_ddNo.setVisible(false);
            }
            
            txt_courseName.setText(""+(rs.getString(7)));
            txt_gstNo.setText(""+(rs.getString(8)));
            txt_tatalAmount.setText(""+(rs.getString(9)));
            txt_date.setText(""+(rs.getString(10)));
            txt_initialAmount.setText(""+(rs.getString(11)));
            txt_cgst.setText(""+(rs.getDouble(12)));
            txt_sgst.setText(""+(rs.getString(13)));
            txt_tatalInWords.setText(""+(rs.getString(14)));
            txt_remark.setText(""+(rs.getString(15)));
            txt_year1.setText(""+(rs.getString(16)));
            txt_year2.setText(""+(rs.getString(17)));
            txt_rollNo.setText(""+(rs.getString(18)));
            
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_print = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_receiptNo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_chequeNo = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_paymentMode = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_bankName = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_courseName = new javax.swing.JLabel();
        txt_chequeNo = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txt_gstNo = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txt_sgst = new javax.swing.JLabel();
        txt_tatalAmount = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txt_initialAmount = new javax.swing.JLabel();
        txt_remark = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txt_year2 = new javax.swing.JLabel();
        txt_recivedFrom = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txt_tatalInWords = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_rollNo = new javax.swing.JLabel();
        txt_ddNo = new javax.swing.JLabel();
        lbl_ddNo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelsideBar = new javax.swing.JPanel();
        panalHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        panalSearchRecord = new javax.swing.JPanel();
        btnSearchRecord = new javax.swing.JLabel();
        panalEditCourses = new javax.swing.JPanel();
        btnEditCourses = new javax.swing.JLabel();
        panalCourseList = new javax.swing.JPanel();
        btnCourseList = new javax.swing.JLabel();
        panalViewAllRecord = new javax.swing.JPanel();
        btnViewAllRecord = new javax.swing.JLabel();
        panalBack = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        panalLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        panalEdit = new javax.swing.JPanel();
        btnEdit = new javax.swing.JLabel();
        panalPrint = new javax.swing.JPanel();
        btnPrint = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Print Recipet");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_print.setBackground(new java.awt.Color(255, 255, 255));
        panel_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("BPHE SOCIETY'S");
        panel_print.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 220, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel9.setText("AHMEDNAGAR");
        panel_print.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 240, 40));

        txt_receiptNo.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txt_receiptNo.setText("ACA");
        panel_print.add(txt_receiptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 250, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/aca2.png"))); // NOI18N
        panel_print.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 190, 190));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel13.setText("Chandni Chowk, Station Road, Nagar, Maharashtra 414001 ");
        panel_print.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 490, 30));

        lbl_chequeNo.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lbl_chequeNo.setText("Cheque Nunber :");
        panel_print.add(lbl_chequeNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 180, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel15.setText("Receipt Number :               ACA-");
        panel_print.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 250, 30));

        txt_paymentMode.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txt_paymentMode.setText("paymode");
        panel_print.add(txt_paymentMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 190, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel17.setText("Date :");
        panel_print.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 80, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel18.setText("Payment Mode :");
        panel_print.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 150, 30));

        txt_bankName.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        panel_print.add(txt_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 420, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel20.setText("Recived From :");
        panel_print.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 170, 30));

        txt_courseName.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txt_courseName.setText("coursename");
        panel_print.add(txt_courseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 170, 30));

        txt_chequeNo.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        panel_print.add(txt_chequeNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 170, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel23.setText("Bank Name :");
        panel_print.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 170, 30));

        txt_date.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txt_date.setText("date");
        panel_print.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 200, 230, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel25.setText("GST Number :");
        panel_print.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, 120, 30));

        txt_gstNo.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txt_gstNo.setText("gstno");
        panel_print.add(txt_gstNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 230, 250, 30));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel27.setText("The following payment in the colledge office for the year");
        panel_print.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 440, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel28.setText("Heads");
        panel_print.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 170, 30));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel29.setText("Amount (Rs)");
        panel_print.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 430, 170, 30));

        txt_year1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txt_year1.setText("2022");
        panel_print.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 50, 30));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel31.setText("Sr.No");
        panel_print.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 170, 30));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel32.setText("CGST 9%");
        panel_print.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 170, 30));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel33.setText("SGST 9%");
        panel_print.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, 170, -1));

        txt_cgst.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txt_cgst.setText("CGST");
        panel_print.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, 170, 30));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel35.setText("1.");
        panel_print.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 170, 30));

        txt_sgst.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txt_sgst.setText("SGST");
        panel_print.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 570, 170, 30));

        txt_tatalAmount.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txt_tatalAmount.setText("TOTALAMOUNT");
        panel_print.add(txt_tatalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 630, 170, 30));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel38.setText("Receiver Signature");
        panel_print.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 860, 170, 30));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel39.setText("Total in words :");
        panel_print.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 130, 30));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel40.setText("Roll Number :");
        panel_print.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, 110, 30));

        txt_initialAmount.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txt_initialAmount.setText("AMOUNT");
        panel_print.add(txt_initialAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 490, 170, 30));

        txt_remark.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txt_remark.setText("remark");
        panel_print.add(txt_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 800, 590, 30));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel43.setText("-");
        panel_print.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 10, 30));

        txt_year2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txt_year2.setText("2023");
        panel_print.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 50, 30));

        txt_recivedFrom.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txt_recivedFrom.setText("recivedfrom");
        panel_print.add(txt_recivedFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 420, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        panel_print.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 840, 370, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        panel_print.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1220, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        panel_print.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 1220, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        panel_print.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 1220, 20));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        panel_print.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 610, 370, 20));

        txt_tatalInWords.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txt_tatalInWords.setText("TOATAAMOUNTINWORDS");
        panel_print.add(txt_tatalInWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 720, 970, 30));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel44.setText("Remark :");
        panel_print.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 800, 90, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel12.setText(" AHMEDNAGAR COLLEGE ");
        panel_print.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 520, 40));

        txt_rollNo.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txt_rollNo.setText("rollno");
        panel_print.add(txt_rollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 300, 170, 30));

        txt_ddNo.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        panel_print.add(txt_ddNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 120, 30));

        lbl_ddNo.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lbl_ddNo.setText("DD Number  :");
        panel_print.add(lbl_ddNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 120, 30));

        getContentPane().add(panel_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 1220, 930));

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 1, 60)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Print Receipt");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 410, 80));

        panelsideBar.setBackground(new java.awt.Color(0, 102, 102));
        panelsideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panalHome.setBackground(new java.awt.Color(0, 102, 102));
        panalHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panalHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btnHome.setText("   Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        panalHome.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 290, 70));

        panelsideBar.add(panalHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 330, 70));

        panalSearchRecord.setBackground(new java.awt.Color(0, 102, 102));
        panalSearchRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panalSearchRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearchRecord.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnSearchRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search2.png"))); // NOI18N
        btnSearchRecord.setText("Search Record");
        btnSearchRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseExited(evt);
            }
        });
        panalSearchRecord.add(btnSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 290, 70));

        panelsideBar.add(panalSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 330, 70));

        panalEditCourses.setBackground(new java.awt.Color(0, 102, 102));
        panalEditCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panalEditCourses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditCourses.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnEditCourses.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCourses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btnEditCourses.setText(" Edit Courses");
        btnEditCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseExited(evt);
            }
        });
        panalEditCourses.add(btnEditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 290, 70));

        panelsideBar.add(panalEditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 330, 70));

        panalCourseList.setBackground(new java.awt.Color(0, 102, 102));
        panalCourseList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panalCourseList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCourseList.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnCourseList.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/list.png"))); // NOI18N
        btnCourseList.setText(" Course List");
        btnCourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCourseListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCourseListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCourseListMouseExited(evt);
            }
        });
        panalCourseList.add(btnCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 300, 70));

        panelsideBar.add(panalCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 330, 70));

        panalViewAllRecord.setBackground(new java.awt.Color(0, 102, 102));
        panalViewAllRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panalViewAllRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewAllRecord.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnViewAllRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view all record.png"))); // NOI18N
        btnViewAllRecord.setText("View All Record");
        btnViewAllRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseExited(evt);
            }
        });
        panalViewAllRecord.add(btnViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 300, 70));

        panelsideBar.add(panalViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 330, 70));

        panalBack.setBackground(new java.awt.Color(0, 102, 102));
        panalBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panalBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/back-button.png"))); // NOI18N
        btnBack.setText("  Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        panalBack.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 290, 70));

        panelsideBar.add(panalBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 330, 70));

        panalLogout.setBackground(new java.awt.Color(0, 102, 102));
        panalLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panalLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        btnLogout.setText("  Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        panalLogout.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 290, 70));

        panelsideBar.add(panalLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 750, 330, 70));

        panalEdit.setBackground(new java.awt.Color(0, 102, 102));
        panalEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panalEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEdit.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btnEdit.setText("  Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMouseExited(evt);
            }
        });
        panalEdit.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 290, 70));

        panelsideBar.add(panalEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 970, 330, 70));

        panalPrint.setBackground(new java.awt.Color(0, 102, 102));
        panalPrint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panalPrint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrint.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/printer-.png"))); // NOI18N
        btnPrint.setText("  Print");
        btnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrintMouseExited(evt);
            }
        });
        panalPrint.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 290, 70));

        panelsideBar.add(panalPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 860, 330, 70));

        getContentPane().add(panelsideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 1090));

        setSize(new java.awt.Dimension(1981, 1101));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        Home home= new Home();
        home.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        Color clr= new Color(0,153,153);
        panalHome.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        Color clr= new Color(0,103,103);
        panalHome.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnSearchRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseClicked
        SearchRecord searchRecord=new SearchRecord();
        searchRecord.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchRecordMouseClicked

    private void btnSearchRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseEntered
        Color clr= new Color(0,153,153);
        panalSearchRecord.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnSearchRecordMouseEntered

    private void btnSearchRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseExited
        Color clr= new Color(0,103,103);
        panalSearchRecord.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnSearchRecordMouseExited

    private void btnEditCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseClicked
        EditCourse ec = new EditCourse();
        ec.show();
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditCoursesMouseClicked

    private void btnEditCoursesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseEntered
        Color clr= new Color(0,153,153);
        panalEditCourses.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnEditCoursesMouseEntered

    private void btnEditCoursesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseExited
        Color clr= new Color(0,103,103);
        panalEditCourses.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnEditCoursesMouseExited

    private void btnCourseListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseClicked
        ViewCourse vc = new ViewCourse();
        vc.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCourseListMouseClicked

    private void btnCourseListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseEntered
        Color clr= new Color(0,153,153);
        panalCourseList.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnCourseListMouseEntered

    private void btnCourseListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseExited
        Color clr= new Color(0,103,103);
        panalCourseList.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnCourseListMouseExited

    private void btnViewAllRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseClicked
        ViewAllRecords allRecords=new ViewAllRecords();
        allRecords.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewAllRecordMouseClicked

    private void btnViewAllRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseEntered
        Color clr= new Color(0,153,153);
        panalViewAllRecord.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnViewAllRecordMouseEntered

    private void btnViewAllRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseExited
        Color clr= new Color(0,103,103);
        panalViewAllRecord.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnViewAllRecordMouseExited

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        Home home= new Home();
        home.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        Color clr= new Color(0,153,153);
        panalBack.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        Color clr= new Color(0,103,103);
        panalBack.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseExited

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked

        Login login=new Login();
        login.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        Color clr= new Color(0,153,153);
        panalLogout.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        Color clr= new Color(0,103,103);
        panalLogout.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        UpdateFeesDetails u=new UpdateFeesDetails();
        u.show();
        this.dispose();
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
        Color clr= new Color(0,153,153);
        panalEdit.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnEditMouseEntered

    private void btnEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseExited
        Color clr= new Color(0,103,103);
        panalEdit.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnEditMouseExited

    private void btnPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseClicked

        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");

        job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                pf.setOrientation(PageFormat.LANDSCAPE);
                if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);

                panel_print.print(g2);

                return Printable.PAGE_EXISTS;

            }
        });
        boolean ok = job.printDialog();
        if(ok){
            try{
                job.print();
            }
            catch (PrinterException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnPrintMouseClicked

    private void btnPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseEntered
        Color clr= new Color(0,153,153);
        panalPrint.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnPrintMouseEntered

    private void btnPrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseExited
        Color clr= new Color(0,103,103);
        panalPrint.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_btnPrintMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReciept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnCourseList;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnEditCourses;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnPrint;
    private javax.swing.JLabel btnSearchRecord;
    private javax.swing.JLabel btnViewAllRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_chequeNo;
    private javax.swing.JLabel lbl_ddNo;
    private javax.swing.JPanel panalBack;
    private javax.swing.JPanel panalCourseList;
    private javax.swing.JPanel panalEdit;
    private javax.swing.JPanel panalEditCourses;
    private javax.swing.JPanel panalHome;
    private javax.swing.JPanel panalLogout;
    private javax.swing.JPanel panalPrint;
    private javax.swing.JPanel panalSearchRecord;
    private javax.swing.JPanel panalViewAllRecord;
    private javax.swing.JPanel panel_print;
    private javax.swing.JPanel panelsideBar;
    private javax.swing.JLabel txt_bankName;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_chequeNo;
    private javax.swing.JLabel txt_courseName;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_ddNo;
    private javax.swing.JLabel txt_gstNo;
    private javax.swing.JLabel txt_initialAmount;
    private javax.swing.JLabel txt_paymentMode;
    private javax.swing.JLabel txt_receiptNo;
    private javax.swing.JLabel txt_recivedFrom;
    private javax.swing.JLabel txt_remark;
    private javax.swing.JLabel txt_rollNo;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_tatalAmount;
    private javax.swing.JLabel txt_tatalInWords;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    // End of variables declaration//GEN-END:variables
}
